---
title: "Hotels"
author: "Joel Soroos"
date: "February 17, 2020"
output: html_document
---

https://juliasilge.com/blog/hotels-recipes/

#1a.  Source data
```{r source, include=FALSE}
   knitr::opts_chunk$set(echo = TRUE)

   library(janitor)

   hotels_raw <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-11/hotels.csv") %>%
      clean_names()
```
 
     
#1b.  Source fonts
```{r}

   library (showtext)
   
   font_add_google("Yanone Kaffeesatz")
   showtext_auto() 
```



#2a.  Isolate required fields, observations
```{r core data, warning = F, results = F, message = F, echo = T}

   library(tidyverse)  
   library(skimr)
   library(GGally)
   library(kableExtra)
   
   hotels_raw %>%
     mutate(
        arrival_date_month = factor(
           arrival_date_month,
            levels = month.name
         )) %>%
     count(hotel, arrival_date_month, children) %>%
     group_by(hotel, children) %>%
     mutate(proportion = n / sum(n)) %>%
     ggplot(aes(arrival_date_month, proportion, fill = children)) +
      geom_col(position = "dodge") +
      scale_y_continuous(labels = scales::percent_format()) +
      facet_wrap(~hotel, nrow = 2) +
      labs(
         x = NULL,
         y = "Proportion of hotel stays",
         fill = NULL
      )
   
   hotels_raw %>%
      skim ()
   
   hotels_raw %>%
     select(is_canceled, required_car_parking_spaces) %>%
     mutate (is_canceled = as.character(is_canceled)) %>%
     ggpairs(mapping = aes(color = is_canceled))
```



#3.  Visualize
```{r visualize, warning = F, results = F, message = F, echo = T}
   
   library(ggraph)
   
   ggraph(routes_tidy) +
      geom_edge_link(
         aes (edge_color = delay_pct),
         edge_width = 0.3, edge_alpha = 0.5
         ) +
      geom_node_point(shape = 1, size = 0.5) +
      geom_node_text(
         aes (label = station),
         size = 2.4, family = "Yanone Kaffeesatz", repel = TRUE
         ) +
      scale_edge_color_viridis(option = "plasma") +
      theme_graph() +
      theme (
         plot.title = element_text(hjust = 0.5, vjust = 0, family = "Yanone Kaffeesatz", size = 15, face = "bold", margin = margin (0,0,0,0)),
         plot.title.position = "plot",
         plot.subtitle = element_text(hjust = 0.5, vjust = 0, size = 11, margin = margin (2,0,12,0), family = "Yanone Kaffeesatz"),
         plot.caption = element_text(hjust = 0, vjust = 1, size = 9, face = "plain", margin = margin (10,0,10,0), family = "Yanone Kaffeesatz"),
         plot.caption.position = "plot",
         legend.title = element_text(size = 9, hjust = 0.5, vjust = 0.5),
         legend.text = element_text(size = 9, hjust = 0.5, vjust = 0.5),
         legend.direction = "horizontal",
         legend.position = c(0.79,.89),
         text = element_text(family = "Yanone Kaffeesatz")
         ) +
      labs(
         title = "High Speed Train Delays en France",
         subtitle = "You will wait the longest when journeying from Lyon Part Dieu to either Montpellier, Marseille St. Charles or Marne La Vallee.",
         caption = "Each node (point) is a train station. Each edge (line) is a route between stations.  Edge width is the average delay as percentage of journey time.\nHigh speed train journeys in France between 2015 and 2018.\nVisualization: Joel Soroos @soroosj  |  Data: National Society of French Railways (SNCF) via R4DS Tidy Tuesday"
         )  +
      ggsave("trains.png", width = , height = , units = "cm")
```   
   
   








