---
   title: "Animated File Media Franchise Revenues"
   author: "Joel Soroos"
   date: "July 7, 2019"
   output: pdf_document
---

### 1. Source data
```{r source, warning = TRUE, results = FALSE, message = FALSE}

   library (tidyverse)
   library (janitor) 

   franchise_raw <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-07-02/media_franchises.csv") %>%
      clean_names ()
```
   
### 2a.  Convert franchise revenues to friendly names
```{r transform, message = F}

   franchise <- franchise_raw %>%
      filter (original_media == "Animated film") %>%
      select (franchise, revenue_category, revenue, year_created) %>%
      mutate (
         franchise = case_when (
            franchise == "Despicable Me / Minions" ~ "Minions",
            franchise == "The Lion King" ~ "Lion King",
            TRUE ~ franchise
            ),
         franchise_start = paste (franchise, "\n(", year_created, ")", sep = ""),
         franchise_start = fct_relevel(franchise_start,              #Control franchise order in chart
            "Barbie\n(1987)", "Cars\n(2006)", "Toy Story\n(1995)", "Lion King\n(1994)", "Frozen\n(2013)", "Minions\n(2010)", "Aladdin\n(1992)", "Ice Age\n(2002)" 
            ),
         revenue = revenue * 10,                 #Multiply by 10 to generate more boxes in waffle chart for additional granularity.
         revenue_category = case_when (
            revenue_category == "Home Video/Entertainment" ~ "Home Video",
            revenue_category == "Video Games/Games" ~ "Video Games",
            revenue_category == "Merchandise, Licensing & Retail" ~ "Merchandise",
            TRUE ~ revenue_category
            ),
         revenue_category = fct_lump (revenue_category,6),
         #control revenue group order in chart
         revenue_category = fct_relevel(revenue_category, "Box Office", "Home Video", "Music", "Video Games", "Merchandise", "Other")   
      ) 
```

#2b.  Prepare counts for waffle chart
```{r}
   franchise_sum <- franchise %>% 
      group_by (franchise_start, revenue_category) %>%
      summarize (sum = sum(revenue)) 
```

#3.  Create chart
```{r chart, warning = TRUE, results = FALSE, message = FALSE}

   library (waffle)
   library (ggdark)

   ggplot(franchise_sum, aes(fill=revenue_category, values=sum)) + 
     geom_waffle(color = "white", size=.3, n_rows = 8, flip = T, show.legend = T, make_proportional = T) +
     facet_wrap(~franchise_start, nrow=1, strip.position = "bottom") +
     #scales
         scale_x_discrete(expand=c(0,0)) +
         scale_y_continuous(
            breaks = seq(5, 50, by = 5), 
            labels = function(x) x * .8, # make this multiplier the same as n_rows
            expand = c(0,0)
            ) +
         scale_fill_brewer(palette = "Set1") +
     #themes
        dark_mode(theme_minimal()) +
        theme(
           #download custom Waltograph font and then upload to R via extrafont package: packagehttps://www.dafont.com/waltograph.font
           text = element_text(family = "Waltograph", color = "white"),   
           plot.title = element_text(hjust = .5, size = 22, face = "bold"),
           plot.caption = element_text(hjust = 1, size = 12, vjust = .5),
           axis.title=element_text(size=11),
           axis.title.x = element_blank(),
           axis.text.x=element_text(size=11),
           axis.title.y = element_text(hjust=1, size = 12, face = "bold"),
           axis.text.y=element_text(size=12, face = "bold"),
           axis.ticks.y = element_line(),
           legend.title = element_text(size=12),
           legend.text = element_text(size=12),
           legend.key.size = unit(0.5, "cm"),
           legend.position = c(0.92,0.67),
           strip.text = element_text(size = 13),
           panel.grid = element_blank()
           ) +
         guides(fill = guide_legend(ncol = 1)) +
         coord_equal() +
     labs(
        title = "Animated Film Franchise Revenues",
        y = "Revenues ($, billions)",
        fill = "",
        caption = "\nEach square represents $100 million in revenues. Year below franchise signifies year of creation. \nSource: Wikipedia  |  Visualization: Joel Soroos @soroosj"
        ) +
      ggsave("franchise.png", width = 15, height = 9.5, units = "cm")
```
