---
title: "French Trains"
author: "Joel Soroos"
date: "January 5, 2020"
output: html_document
---

#1a.  Source data
```{r source, include=FALSE}
   knitr::opts_chunk$set(echo = TRUE)

   library(tidytuesdayR)
   library(janitor)

   tuesdata <- tidytuesdayR::tt_load('2019-02-26')
   trains_raw <- tuesdata$full_trains %>%
      clean_names()
```
 
     
#1b.  Source fonts
```{r}

   library (showtext)
   
   font_add_google("Yanone Kaffeesatz")
   showtext_auto() 
```



#2a.  Isolate required fields, observations
```{r core data, warning = F, results = F, message = F, echo = T}

   library(tidyverse)  
 
   trains <- trains_raw %>%
      rename (
         trips = total_num_trips,
         journey_time = journey_time_avg,
         delay_abs = avg_delay_all_arriving
         ) %>%
      mutate(
         departure_station = str_to_title (departure_station),
         arrival_station = str_to_title (arrival_station),
         delay_pct = delay_abs / journey_time * 100
          ) %>%
      select (year, month, departure_station, arrival_station, delay_pct) 
```


#2b.  Compile unique stations (nodes)
```{r network}

   #unique departure stations
      departures <- trains %>%
         distinct(departure_station) %>%
         rename(station = departure_station)

   #unique arrival stations
      arrivals <- trains %>%
         distinct(arrival_station) %>%
         rename(station = arrival_station)

   #combined arrival/departures stations with unique station ID
      nodes <- full_join(departures, arrivals, by = "station") %>%
          rowid_to_column("id")
```   
 

#2c.  Create list of routes (edges)
```{r edges}

   #sum trips per route
      per_route <- trains %>%  
        group_by(departure_station, arrival_station) %>%
        summarise(
           delay_pct = mean(delay_pct)
           ) %>% 
        ungroup()

   #append station ID to routes
      edges <- per_route %>% 
        left_join(nodes, by = c("departure_station" = "station")) %>% 
        rename(from = id) %>% 
        left_join(nodes, by = c("arrival_station" = "station")) %>% 
        rename(to = id) %>%
        select(from, to, delay_pct)
```


#2d.  Combine nodes, edges into required format for network diagram
```{r}

   library(tidygraph)
   
   routes_tidy <- tbl_graph(nodes = nodes, edges = edges, directed = TRUE)
```


#3.  Visualize
```{r visualize, warning = F, results = F, message = F, echo = T}
   
   library(ggraph)
   
   ggraph(routes_tidy) +
      geom_edge_link(
         aes (edge_color = delay_pct),
         edge_width = 0.3, edge_alpha = 0.5
         ) +
      geom_node_point(shape = 1, size = 0.5) +
      geom_node_text(
         aes (label = station),
         size = 2.4, family = "Yanone Kaffeesatz", repel = TRUE
         ) +
      scale_edge_color_viridis(option = "plasma") +
      theme_graph() +
      theme (
         plot.title = element_text(hjust = 0.5, vjust = 0, family = "Yanone Kaffeesatz", size = 15, face = "bold", margin = margin (0,0,0,0)),
         plot.title.position = "plot",
         plot.subtitle = element_text(hjust = 0.5, vjust = 0, size = 11, margin = margin (2,0,12,0), family = "Yanone Kaffeesatz"),
         plot.caption = element_text(hjust = 0, vjust = 1, size = 9, face = "plain", margin = margin (10,0,10,0), family = "Yanone Kaffeesatz"),
         plot.caption.position = "plot",
         legend.title = element_text(size = 9, hjust = 0.5, vjust = 0.5),
         legend.text = element_text(size = 9, hjust = 0.5, vjust = 0.5),
         legend.direction = "horizontal",
         legend.position = c(0.79,.89),
         text = element_text(family = "Yanone Kaffeesatz")
         ) +
      labs(
         title = "High Speed Train Delays en France",
         subtitle = "You will wait the longest when journeying from Lyon Part Dieu to either Montpellier, Marseille St. Charles or Marne La Vallee.",
         caption = "Each node (point) is a train station. Each edge (line) is a route between stations.  Edge width is the average delay as percentage of journey time.\nHigh speed train journeys in France between 2015 and 2018.\nVisualization: Joel Soroos @soroosj  |  Data: National Society of French Railways (SNCF) via R4DS Tidy Tuesday"
         )  +
      ggsave("trains.png", width = , height = , units = "cm")
```   
   
   




