---
title: "The Office"
author: "Joel Soroos"
date: "3/17/2020"
output: html_document
---

### 1. Source data
```{r source, warning = TRUE, results = TRUE, message = FALSE}

   library(tidyverse)
   library(janitor)
   library(schrute)
   library(knitr)
   
   opts_chunk$set(warning = FALSE, message = FALSE, results = TRUE)

   office_raw <- schrute::theoffice %>%
      clean_names()

   glimpse (office_raw)
```


### 2.  Transform stage data
```{r transform, warning = TRUE, results = FALSE, message = FALSE}

   office_episode <- office_raw %>%
      select (season, episode, episode_name, air_date, director, writer, character, imdb_rating) %>%
      distinct (episode_name, .keep_all = T)

   office_season %>%
      group_by (season) %>%
      summarize (n = n (), avg = mean(imdb_rating), sd = sd(imdb_rating)) %>%
      arrange (-avg)
```

```{r}
   office_characters <-
      office_raw %>%
      count (episode_name, character) %>%
      add_count (character, wt = n, name = "sum") %>%
      filter (sum > 800) %>%
      select (-sum) %>%
      #group_by (episode_name) %>%
         #mutate (pct = n/sum(n)) %>%
      #ungroup (episode_name) %>%
      arrange (episode_name, -n) %>%
      pivot_wider (names_from = character, values_from = n, values_fill = list(n=0)) 

   office_characters
```
```{r}
   
   office_full <- 
      inner_join (office_episode, office_characters) %>%
      select (-season, -episode, -air_date, -director, -writer, -character)

   office_full
```

```{r}
   library (tidymodels)

   office_split <- initial_split (office_full)
```


