---
title: "Plastic Waste"
output:
  html_document: default
  author: Joel Soroos
---

### 1. Load packages
```{r setup, warning = FALSE, results = FALSE, message = FALSE}

   library (tidyverse)
   library (janitor)
   library (ggthemes)
   library (ggrepel)
   library (scales)
   library (countrycode)

```

### 2. Get data
```{r source, warning = TRUE, results = FALSE, message = FALSE}

waste_raw <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/per-capita-mismanaged-plastic-waste-vs-gdp-per-capita.csv") %>%
   clean_names()
   
```

### 3. Transform data
```{r transform}

waste <- waste_raw %>%
   rename (
      country_name = entity,
      country_code = code,
      waste_per_capita = per_capita_mismanaged_plastic_waste_kilograms_per_person_per_day,
      gdp_per_capita = gdp_per_capita_ppp_constant_2011_international_rate,
      population = total_population_gapminder
      )%>%
   mutate (
      waste_per_capita = waste_per_capita * 100,
      population = population / 1000000
      ) %>%
   select (country_name, waste_per_capita, gdp_per_capita, population) %>%
   arrange (country_name) %>%
   drop_na (waste_per_capita)

```


### 4. Create ridgeline chart by continent
```{r plot}

plot1 <- ggplot (waste,
   aes(x = gdp_per_capita, y = waste_per_capita, size = population)) +
   geom_point () +
   geom_smooth () +
   scale_x_continuous(
      trans = log10_trans(),
      labels = comma
      ) +
   scale_y_continuous(trans = log10_trans()) +
   scale_size_continuous(breaks = c(50, 100, 500, 1500)) +
   theme_economist_white () +
   geom_label_repel(
      aes (label = country_name),
      data = subset (waste, 
                     waste_per_capita > 20 |
                     waste_per_capita < .2 |
                     country_name == "India"
                     ),
      box.padding = 0.5, 
      point.padding = 0.5,
      alpha = 0.6,
      size = 3,
      segment.color = 'grey50'
      ) +
   theme(
      legend.title = element_text(colour="black", size=9),
      legend.text = element_text(colour="black", size=9)
      ) +
   labs(
      title = "Mismanaged waste decreases as GDP increases (2010)",
      caption = "\n Source:National Geographic  |  R4DS Tidy Tuesday
      Visualization: Joel Soroos (Twitter: @soroosj)",
      x = "GDP per capita ($)",
      y = "Mismanaged waste per capita (100kg/day)",
      size = "Population (millions): "
      )

plot1
ggsave("plot1.png",plot1)
```
