---
title: "Student Ratio"
output:
  html_document: default
---

### 1. Load packages
```{r setup, warning = FALSE, results = FALSE, message = FALSE}

library (tidyverse)
library (janitor)
library (inspectdf)
library (ggridges)
library (ggthemes)
library (countrycode)

```

### 2. Source data
```{r source, warning = FALSE, results = FALSE, message = FALSE }

student_raw <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-07/student_teacher_ratio.csv")%>%
   clean_names()

inspect_cat (student_raw, show_plot = T)
inspect_num (student_raw, show_plot = T)
inspect_na (student_raw, show_plot = T)

   
```

### 3. Transform data
```{r transform}

student <- student_raw %>%
   mutate (
      continent = countrycode(country, origin = "country.name", destination = "continent"),
      indicator = str_replace (indicator, " Education", ""),
      indicator = as.factor(indicator),
      indicator = fct_relevel(indicator, c("Pre-Primary", "Primary", "Lower Secondary", "Secondary", "Upper Secondary", "Post-Secondary Non-Tertiary", "Tertiary"))
      )%>%
   select (continent, country_code, country, indicator, year, student_ratio) %>%
   drop_na ()

```


### 4a. Create ridgeline chart by continent
```{r plot1}

continent_plot <- student %>%
   filter (
      year == 2016,
      indicator == "Upper Secondary"
      ) %>%
   ggplot (aes(x = student_ratio, y = reorder(continent,desc(continent)), group = continent)) +
   geom_density_ridges (fill = "skyblue") +
   theme_economist() +
   labs(
      title = "Upper Secondary Student/Teacher Ratio by Continent (2016)",
      subtitle = "Oceania has the most dispersion, Europe the least.",
      caption = "\n Source:UNESCO Institute of Statistics  |  R4DS Tidy Tuesday
      Visualization: Joel Soroos (Twitter @soroosj)",
      x = "Student Teacher Ratio",
      y = "") 

ggsave ("plots/continent.png", continent_plot)

continent_plot

```

### 4b. Create ridgeline chart by indicator
```{r plot2}

indicator_plot <- student %>%
   filter (
      year == 2016,
      continent == "Asia"
      ) %>%
   ggplot (aes(x = student_ratio, y = reorder(indicator,desc(indicator)), group = indicator)) +
   geom_density_ridges (fill = "skyblue") +
   theme_economist() %>%
   labs(
      title = "Student/Teacher Ratio by Education Level in Asia (2016)",
      caption = "Source:UNESCO Institute of Statistics  |  R4DS Tidy Tuesday
      Visualization: Joel Soroos @soroosj",
      x = "",
      y = "")

ggsave ("plots/indicator.png", indicator_plot)

indicator_plot

```