---
   title: "Vehicle Miles Per Gallon Efficiency"
   author: "Joel Soroos"
   date: "October 20, 2019"
   output: pdf_document
---


### 1. Source data
```{r source, warning = TRUE, results = FALSE, message = FALSE}

   library (tidyverse)
   library (janitor) 
   library (jpeg)
   library (grid)
   library (magick)

   cars_raw <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-10-15/big_epa_cars.csv")%>%
      clean_names () 
   	
   pump_img <- image_read("petrol-pump.jpg") %>%
      rasterGrob(width = unit(2,"in"))
```


### 2.  Transform data
```{r transform, message = F, results = F}

   cars <- cars_raw %>%
      select(id, make, model, eng_dscr, year, cylinders, v_class, displ, fuel_type1, comb08) %>%
      filter (year == 2019) %>%
      rename (
         mph_comb = comb08,
         fuel_type = fuel_type1,
         engine = eng_dscr
         ) %>%
      mutate (
         v_class = str_remove(v_class, " 2WD"),
         v_class = str_remove(v_class, " 4WD")
         ) 
```


###3.  Model data
```{r}

   library (broom)

   cars_lm <- lm (mph_comb ~ v_class + fuel_type, cars)
   
   cars_tidy <- tidy(cars_lm) %>%
      mutate (
         term = str_remove(term, "fuel_type"),
         term = str_remove(term, "v_class"),
         term = str_remove(term, " -"),
         term = fct_reorder(term, estimate),
         estimate_direction = ifelse(estimate >=0, "positive", "negative")
         ) %>%
      arrange (term)
```


### 4. Visualize data
```{r}

   ggplot(data = cars_tidy, aes(y = estimate, x = term, fill = estimate_direction)) +
      geom_col() +
      coord_flip () +
      annotation_custom (pump_img, ymin = -10, xmin = -2) +
      #scales
         scale_y_continuous(limits = c (-20, 80)) +
         scale_fill_manual(values = c("red", "darkgreen")) +
         scale_color_manual(values = c("red", "darkgreen")) +
      theme(
            plot.title = element_text(hjust = 0, vjust = 0, size = 17, face = "bold", margin = margin (0,0,3,0)),
            plot.subtitle = element_text(hjust = 0, vjust = 0, size = 10, face = "bold", margin = margin (0,0,25,0)),
            plot.caption = element_text (hjust = 0, size = 8, face = "plain", margin = margin (20,0,0,0)),
            plot.title.position = "plot",
            plot.caption.position = "plot",
            panel.background = element_rect (fill = "white"),
            axis.line = element_line(color = "gray70"),
            axis.ticks = element_line(color = "gray70"),
            axis.title = element_text (size = 9, hjust = 0.75, color = "gray20"),
            legend.position = "none"
            ) +
      labs(
         title = "How does your vehicle choice impact fuel efficiency?",
         subtitle = "Electric cars contribute most marginal miles per hour on average, vans and pickup trucks detract most.",
         x = "Regression term",
         y = "Estimated marginal contribution (detraction) to mph",
         caption = "Each row represents linear regression estimate of vehicle class & gasoline type indepedent variables vs. miles per gallon dependent variable.\nVisualization: Joel Soroos @soroosj  |  Data: U.S. EPA via R4DS Tidy Tuesday"
         ) +
      ggsave("cars.png", width = 18, height = 13, units = "cm")
```












