---
title: "Astronauts"
author: "Joel Soroos"
date: "8/21/2020"
output: html_document
---


```{r source, warning = FALSE, message = FALSE}

   library(tidyverse)
   library(here)

   #download astronaut mission data
   astronaut_raw <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-07-14/astronauts.csv')
   
   #download astronaut photos
   astronaut_photos <- read_csv(here("2020-07-14", "source", "astronaut photos.csv"))
   
   #download outer space image for chart background
   space_img <- "https://cdn.wallpapersafari.com/83/9/z8eIEZ.jpg"
```


```{r explore}

   library(skimr)
   library(here)

   #skim (astronaut_raw)
```


```{r transform}

   library (glue)
   library (countrycode)
   
   #https://en.wikipedia.org/wiki/List_of_spaceflight-related_accidents_and_incidents
   astronaut_fatality <- astronaut_raw %>%
      filter (mission_title %in% c("Soyuz 1","Soyuz 11","STS-107", "STS-51L","STS-51-L", "STS 51-L")) %>%
      pull (name)

   astronaut <- astronaut_raw %>%
      group_by (name) %>%
      arrange (-mission_number) %>%
      filter (name %in% astronaut_fatality)%>%
      slice(1) %>%
      mutate (
         name_clean = glue ("{word(name,2)} {word (name, 1)}"),
         name_clean = str_remove(name_clean,","),
         year_of_mission = if_else(year_of_mission == 1985, 1986, year_of_mission),
         birth_death = glue ("{year_of_birth} - {year_of_mission}"),
         nationality_name = ifelse (nationality == "U.S.S.R/Russia", "Russia",nationality),
         nationality_code = countrycode(nationality_name, origin = "country.name", destination = "iso2c"),
         number_global_nation = glue ("{nationwide_number}/{number}"),
         mission_hours = round(total_hrs_sum,0),
         mission_hours_count= glue ("{total_number_of_missions}/{mission_hours}"),
         mission_title = recode (mission_title, "STS-51-L" = "STS-51L", "STS 51-L" = "STS-51L")
         ) %>%
      left_join (astronaut_photos) %>%
      ungroup (name) %>%
      select (name_clean, birth_death, nationality_code, number_global_nation, mission_title, year_of_mission, mission_hours_count, photo) %>%
      arrange (mission_title, name_clean)
      #head(2)
```


```{r visualize}

   library (ggimage)
   library (cowplot)
   library (showtext)
   
   font_add("Lato", "Lato-Regular.ttf")
   showtext_auto() 

   astronaut_plot <-
      ggplot (astronaut) +
         #add box header
            geom_rect(aes (xmin = 0, xmax = 1, ymin = 0, ymax = 1, fill = mission_title, color = mission_title), size = 4) +
         #add astronaut name
            geom_text(aes (x = 0.5, y = 0.97, label = name_clean), size = 6, hjust = 0.5, color = "white") +
         #add astronaut years of life
            geom_text(aes (x = 0.5, y = 0.88, label = birth_death), size = 6, hjust = 0.5, vjust = 1, color = "white") +
         #add country flag
            geom_flag(aes (x = 0.09, y = 0.81, image = nationality_code), size = 0.17, hjust = 0.5) +
         #add astronaut photo
            geom_image(aes(x=0.5, y=0.4, image = photo), size = 0.41) +
         #add astronaut sequence number
            geom_text(aes (x = 0, y = 0, label = number_global_nation), size = 5, hjust = 0, vjust = 0, color = "white", family = "Lato") +
         #add number of missions
            geom_text (aes (x = 1, y = 0, label = mission_hours_count), size = 5, hjust = 1, vjust = 0, color = "white", family = "Lato") +
         scale_color_viridis_d (end = .6) +
         scale_fill_viridis_d (end = .6) +
         labs(
            title = "IN MEMORY OF THE 18 ASTRONAUTS WHO DIED IN SPACE",
            subtitle = "Soyuz 1: parachute failure upon landing.\nSoyuz 11: suffocation due to a faulty valve during landing.\nSTS-107: Space Shuttle Challenger destroyed 73 seconds after lift-off due to failed O-ring seal.\nSTS-51L: Space Shuttle Columbia broke apart during rentry due to thermal protection system damage.",
            caption = "Visualization: Joel Soroos @soroosj  |  Data: Astronaut Database, Wikipedia"
            ) +
         theme_void() +
         theme (
            plot.title = element_text (color = "white", margin = margin(0,0,5,0), hjust = 0.5, size = 29, family = "Lato"),
            plot.subtitle = element_text (color = "white", margin = margin(0,0,37,0), hjust = 0.5, size = 14, family = "Lato"),
            plot.caption = element_text (color = "white", margin = margin(36,0,3,0), hjust = 0.5, size = 11, family = "Lato"),
            strip.background = element_blank(),
            strip.text = element_blank(),
            legend.title = element_blank(),
            legend.text = element_text(color = "white", hjust = 0, size = 13, family = "Lato"),
            legend.position = c(.98, .03),
            legend.justification = "right",
            legend.direction = "horizontal"
            ) +
         facet_wrap (vars(year_of_mission, mission_title, name_clean)) 

   #add outer space background
   astronaut_plot_2 <-  ggbackground (astronaut_plot, space_img, alpha = 0.2)
      
   #add label/line keys
   ggdraw(astronaut_plot_2) +
      draw_label("Astronaut number: country/global", x = .73, y = .16, color = "white") +
      draw_line(x = c(0.76, 0.76), y = c(0.22, 0.26), color = "white") +
      draw_label("Number of missions / total mission hours", x = .84, y = .21, color = "white") +
      draw_line(x = c(0.64, 0.64), y = c(0.17, 0.26), color = "white")
   
   ggsave(here("2020-07-14", "output", "astronaut.png"), height = 11, width = 12)
```