---
title: "Crop Yields"
author: "Joel Soroos"
date: "9/30/2020"
output: html_document
---


##1. Source data
```{r source, warning = FALSE, message = FALSE}

   library(tidytuesdayR)
   library(janitor)

   tuesdata <- tidytuesdayR::tt_load('2020-09-01') 
   
   crops_raw <- tuesdata$key_crop_yields %>%
      clean_names()
```


##2. Exploratory data analysis
```{r skim, warning = F, message =F}

   library(skimr)

   #skim (crops_raw)
```


##3a. Transform data
```{r transform, message = F}

   library(tidyverse)
   library (glue)

   crops <- crops_raw %>%
      pivot_longer (cols = 4:14, names_to = "commodity", values_to = "yield") %>%
      rename (country = entity) %>%
      mutate (
         commodity = if_else (commodity == "cocoa_beans_tonnes_per_hectare", word(commodity, 1, sep = "_"), word (commodity, sep = "_")),
         commodity = str_to_title(commodity),
         decade = glue("d_{floor(year/10)*10}s")
         ) %>%
      drop_na () %>%
      filter (commodity == "Bananas")%>%
      select (country, commodity, decade, year, yield)

#https://gist.github.com/jthomasmock/5bba85b2ef3fdad94dce9c428b092a93
#https://pbs.twimg.com/media/EiEhaOLXcAA5On3?format=jpg&name=4096x4096
```

```{r}

   crops_nest <- crops %>%
      nest (data = -country) %>%
      mutate (
         plot_code = map(data, ~ggplot(., aes(year, yield)) +
            geom_point(color = "blue") +
            theme(legend.position = "none")
            )
         ) %>%
      select (-data)
```



##3b. Calculate medians by decade
```{r}
   
   crops_mean <- crops %>%
      group_by (country, decade) %>%
      summarize (mean = round(mean (yield),1)) %>%
      pivot_wider (names_from = decade, values_from = mean) %>%
      ungroup() %>%
      rowwise(country) %>%
      mutate (
         mean = mean (c(d_1960s,d_1970s,d_1980s,d_1990s,d_2000s,d_2010s), na.rm = T),
         mean = round (mean, 1),
         st_dev = sd (c(d_1960s,d_1970s,d_1980s,d_1990s,d_2000s,d_2010s), na.rm = T),
         st_dev = round (st_dev, 1),
         plot_image = NA
         ) %>%
      rowid_to_column("rank") %>%
      select(country, rank, mean, st_dev, d_1960s,d_1970s,d_1980s,d_1990s,d_2000s,d_2010s, plot_image) %>%
      head (20) %>%
      left_join (crops_nest)
```


#4.  Visualize
```{r}

   library(gt)
   library(here)

   crops_mean %>%
      ungroup() %>%
      gt () %>%
         data_color(
            columns = c(3, 5:10),
            colors = scales::col_numeric(
               palette = c("#ffffff", "#f2fbd2", "#c9ecb4", "#93d3ab", "#35b0ab"),
               na.color = "gray94",
               domain = NULL
               ) 
            ) %>%
         tab_header (title =  md("**Long-Term Top Yielding Banana-Producing Countries**")) %>%
         tab_source_note ("Table: Joel Soroos @soroosj  | Data: Our World in Data") %>%
         tab_footnote(
           footnote = "2010s includes stub period from 2010-2018.",
           locations = cells_column_labels(columns = vars(d_2010s))
            ) %>%
         tab_spanner(
           label = md("Average by Decade"),
           columns = 5:10
            ) %>%
         tab_spanner(
           label = md("All Periods"),
           columns = 2:4
            ) %>%
         text_transform(
            locations = cells_data(columns = vars(plot_image)),
            fn = function(x) {map(crops_mean$plot_code, ggplot_image, height = px(200))}
            ) %>%
         cols_hide(vars(plot_code)) %>%
         tab_style(
            style = list(
              cell_borders(
                sides = c("left", "right"),
                color = "black",
                weight = px(2)
               )
              ),
            locations = cells_body(columns = vars(mean))
            )%>%
        cols_label(rank = "Rank", country = "Country", d_1960s = "1960s", d_1970s = "1970s", d_1980s = "1980s", d_1990s = "1990s", d_2000s = "2000s", d_2010s = "2010s", mean = "Avg", st_dev = "St Dev") %>%
        
      gtsave(here("2020-09-01","output","crops.png"))
```