---
title: "Tour de France"
author: "Joel Soroos"
date: "4/12/2020"
output: html_document
---

### 1. Source data
```{r source, warning = TRUE, results = FALSE, message = FALSE}

   library(tidyverse)
   library(ggmap)
   library(janitor)

   stages_raw <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-07/tdf_stages.csv") %>%
      clean_names()
   
   winners_raw <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-04-07/tdf_winners.csv") %>%
      clean_names()
   
   register_google(key = Sys.getenv("GOOGLE_MAPS_API"))
   
   year_select <- c(2014:2015)
```


### 2.  Transform stage data
```{r source, warning = TRUE, results = FALSE, message = FALSE}

   library (lubridate)
   library (glue)

   stages <- stages_raw %>%
      mutate (
         year = year(date),
         stage = as.integer(stage),
         winner = str_extract(winner,"[ ].+")
         ) %>%
      filter (year %in% year_select) %>%
      select (year, stage, origin, destination, winner) %>%
      arrange (year, stage)

   cities_origin <- stages %>% 
      distinct (origin) %>%
      rename (city = origin)

   cities_destination <- stages %>% 
      distinct (destination) %>%
      rename (city = destination)
      
   cities_all <- 
      full_join (cities_origin, cities_destination) %>%
      mutate_geocode(city) %>%
      mutate (city_corrected = ifelse(lon < -10, glue ("{city}, Europe"), city)) %>%
      mutate_geocode (city_corrected) %>%
      select (-lat, -lon, -city_corrected) %>%
      rename (lat = lat1, lon = lon1)
   
   stages <- 
      left_join (stages, cities_all, by = c("origin" = "city")) %>%
      rename (origin_lat = lat, origin_lon = lon) %>%
      left_join (cities_all, by = c("destination" = "city")) %>%
      rename (destination_lat = lat, destination_lon = lon) %>%
      select (year, stage, origin, destination, origin_lat, origin_lon, destination_lat, destination_lon, winner) %>%
      arrange (year, stage)
```

### 3.  Transform winners data
```{r, warning = TRUE, results = FALSE, message = FALSE}

   library (gridExtra)

   winners <- winners_raw %>%
      mutate (year = year(start_date)) %>%
      filter (year %in% year_select) %>%
      rename (
         name = winner_name,
         team = winner_team
         ) %>%
      mutate (
         time_margin = round (time_margin,2),
         time_margin = glue ("{time_margin} hours"),
         time_overall = round (time_overall,2),
         time_overall = glue ("{time_overall} hours"),
         name_full = glue ("Winner: {name} ({str_trim(nationality)})"),
         time_margin = glue ("Winning Margin: {time_margin}"),
         time_overall = glue ("Overall Time: {time_overall}"),
         stage_wins = glue ("Stage Wins: {stage_wins}")
         ) %>%
      select (year, name, name_full, nationality, stage_wins, time_margin, time_overall, stage_wins)
   
   stages_full <- left_join (stages, winners, by = "year")
```


### 4. Visualize data
```{r visualize, warning = TRUE, results = FALSE, message = FALSE}

   library (gganimate)
   library (ggrepel)
   library (ggdark)
   library (gifski)
   library (grid)

   tour_map <- ggmap(
      get_googlemap(
         center = c("France"),
         zoom = 5, scale = 2, color = 'bw',
         maptype ='roadmap',
         style = 'style=feature:all|element:labels|visibility:off'
         )
      ) +
      geom_segment(
         data = stages_full,
         aes (
            x = origin_lon, xend = destination_lon,
            y = origin_lat, yend = destination_lat,
            group = year
            ),
         color = "blue", size = 1, alpha = 0.23,
         arrow = arrow(length=unit(0.20,"cm"), type = "closed")
         ) +
      geom_text_repel (
         data = stages_full,
         aes (
            x = (origin_lon + destination_lon)/2, 
            y = (origin_lat + destination_lat)/2, 
            label = winner, group = year
            ),
         color = "red", size = 4, alpha = 0.7, fontface = "bold"
         ) +
      geom_text (
         data = stages_full,
         aes (
            x = (origin_lon + destination_lon)/2, 
            y = (origin_lat + destination_lat)/2, 
            label = stage, group = year
            ),
         color = "blue", size = 5, alpha = 0.5, fontface = "bold"
         ) +
      geom_text (
         data = winners,
         aes (label = name_full, group = year),
         color = "black", size = 5, x = 4, y = 54.85
         )+
      geom_text (
         data = winners,
         aes (label = time_overall, group = year),
         color = "black", size = 5, x = 4, y = 54.5
         )+
      geom_text (
         data = winners,
         aes (label = time_margin, group = year),
         color = "black", size = 5, x = 4, y = 54.15
         )+
      geom_text (
         data = winners,
         aes (label = stage_wins, group = year),
         color = "black", size = 5, x = 4, y = 53.80
         )+
      scale_x_continuous(limits = c(-7, 12)) +
      scale_y_continuous(limits = c(40, 55)) +
      dark_mode(theme_minimal()) +
      theme(
         plot.title = element_text(hjust = 0.5, vjust = 0, size = 20, face = "bold", margin = margin (0,0,4,0)),
         plot.caption = element_text (hjust = 0, size = 10, margin = margin (10,0,0,0), color="white"),
         axis.title=element_blank(),
         axis.text=element_blank(),
         axis.ticks=element_blank(),
         legend.title=element_blank()
         ) +
      transition_states(year, transition_length = 5, state_length = 5, wrap = F) +
      labs(
         title = "Tour De France - {closest_state}",
         caption = "Visualization: Joel Soroos @soroosj  |  Data: Wikipedia, TDF Package, R4DS Tidy Tuesday"
         )

      animate(
         tour_map, 
         renderer = gifski_renderer("tour.gif"),
         duration = 30, nframes = 10,
         height = 900, width = 650
         )
      #https://milosvil.github.io/2018-01-04/Traffic-collisions-in-Belgrade
```

