---
title: "Tour de France - Visualize"
author: "Joel Soroos"
date: "4/12/2020"
output: html_document
---

### 1. Source data
```{r source, warning = TRUE, results = FALSE, message = FALSE}

   library(tidyverse)
   library(ggmap)
   library(here)

   #source from wrangle.Rmd
   stages_full <- read_csv(here("2020-04-07", "data", "stages_full.csv"))
   winners <- read_csv(here("2020-04-07", "data", "winners.csv"))
   
   register_google(key = Sys.getenv("GOOGLE_MAPS_API"))
```   
   

### 2. Visualize data
```{r visualize, warning = TRUE, results = FALSE, message = FALSE}

   library (gganimate)
   library (ggrepel)
   library (ggtext)
   library (ggdark)
   library (gifski)
   library (grid)

   tour_map <- ggmap(
      get_googlemap(
         center = c("France"),
         zoom = 5, scale = 2, color = 'bw',
         maptype ='roadmap',
         style = 'style=feature:all|element:labels|visibility:off'
         )
      ) +
      geom_segment(
         data = stages_full,
         aes (
            x = origin_lon, xend = destination_lon,
            y = origin_lat, yend = destination_lat,
            group = year
            ),
         color = "blue", size = 1, alpha = 0.25,
         arrow = arrow(length=unit(0.25,"cm"), type = "closed")
         ) +
      geom_text (
         data = stages_full,
         aes (
            x = (origin_lon*8/10 + destination_lon*2/10), 
            y = (origin_lat*8/10 + destination_lat*2/10), 
            label = stage, group = year
            ),
         color = "darkgreen", size = 5, alpha = 1.0, fontface = "bold"
         ) +
      geom_text_repel (
         data = stages_full,
         aes (
            x = (origin_lon + destination_lon)/2, 
            y = (origin_lat + destination_lat)/2, 
            label = winner, group = year, seed = 124
            ),
         color = "red", size = 4, alpha = 0.9, fontface = "bold", seed=123
         ) +
      geom_text (
         data = winners,
         aes (label = name_full, group = year),
         color = "black", size = 4.25, x = 3.25, y = 53.40, fontface = "bold"
         )+
      geom_text (
         data = winners,
         aes (label = time_margin, group = year),
         color = "black", size = 4.25, x = 3.25, y = 53.15, fontface = "bold"
         )+
      geom_text (
         data = winners,
         aes (label = time_overall, group = year),
         color = "black", size = 4.25, x = 3.25, y = 52.90, fontface = "bold"
         )+
      geom_text (
         data = winners,
         aes (label = stage_wins, group = year),
         color = "black", size = 4.25, x = 3.25, y = 52.65, fontface = "bold"
         )+
      scale_x_continuous(limits = c(-4.6, 9.47)) +
      scale_y_continuous(limits = c(41.3, 53)) +
      theme(
         plot.title = element_text(hjust = 0.5, vjust = 0, size = 27, face = "bold", margin = margin (0,0,7,0)),
         plot.subtitle = element_markdown(hjust = 0.5, vjust = 0, size = 15, margin = margin (0,0,25,0)),
         plot.caption = element_text (hjust = 0.5, size = 12, margin = margin (9,0,0,0), color="black"),
         axis.title=element_blank(),
         axis.text=element_blank(),
         axis.ticks=element_blank(),
         legend.title=element_blank()
         ) +
      transition_states(year, transition = 0) +
      labs(
         title = "Tour De France - {closest_state}",
         subtitle = "Overall Tour winner statistics denoted in black at top (in North Sea).  \nStage winners listed in <span style = 'color:red;'>red</span>, stage path in <span style = 'color:blue;'>blue</span> and stage numbers in <span style = 'color:darkgreen;'>green</span>.",
         caption = "Visualization: Joel Soroos @soroosj  |  Data: R4DS Tidy Tuesday via TDF Package via Wikipedia"
         )

      animate(
         tour_map, 
         renderer = gifski_renderer(here("2020-04-07", "output", "tour.gif")),
         duration = 300, nframes = 104, height = 800, width = 550
         )
      #https://milosvil.github.io/2018-01-04/Traffic-collisions-in-Belgrade
```

