---
title: "Crop Yields"
author: "Joel Soroos"
date: "9/30/2020"
output: html_document
---


##1. Source data
```{r source, warning = FALSE, message = FALSE}

   library(tidytuesdayR)
   library(janitor)

   tuesdata <- tidytuesdayR::tt_load('2020-09-01') 
   
   crops_raw <- tuesdata$key_crop_yields %>%
      clean_names()
```


##2. Exploratory Data Analysis
```{r skim, warning = F, message =F}

   library(skimr)

   #skim (crops_raw)
```


##3a. Transform data
```{r transform, message = F}

   library(tidyverse)
   library (countrycode)
   library (glue)

   crops <- crops_raw %>%
      pivot_longer (cols = 4:14, names_to = "commodity", values_to = "yield") %>%
      rename (country = entity) %>%
      mutate (
         commodity = if_else (commodity == "cocoa_beans_tonnes_per_hectare", word(commodity, 1, sep = "_"), word (commodity, sep = "_")),
         commodity = str_to_title(commodity),
         #continent = countrycode (code, origin = 'iso3c', destination = 'continent'),
         #region = countrycode (code, origin = 'iso3c', destination = 'region23'),
         decade = glue("d_{floor(year/10)*10}s")
         ) %>%
      drop_na () %>%
      filter (commodity == "Wheat")%>%
      select (continent, region, country, commodity, decade, year, yield) %>%
      arrange (continent, region, country, commodity, year)
```


##3b. Calculate medians by decade
```{r}
   
   crops_mean <- crops %>%
      group_by (continent, region, decade) %>%
      summarize (mean = round(mean (yield),2)) %>%
      pivot_wider (names_from = decade, values_from = mean) %>%
      ungroup() %>%
      rowwise(region) %>%
      mutate (
         mean = mean (c(d_1960s,d_1970s,d_1980s,d_1990s,d_2000s,d_2010s), na.rm = T),
         mean = round (mean, 2)
         )
```


#4.  Visualizing
```{r}

   library(gt)

   crops_mean %>%
      group_by (continent) %>%
      gt () %>%
         summary_rows(
            groups = TRUE,
            columns = vars(d_1960s,d_1970s,d_1980s,d_1990s,d_2000s,d_2010s),
            fns = list(mean = ~mean(.)),
            ) %>%
         data_color(
            columns = vars(d_1960s,d_1970s,d_1980s,d_1990s,d_2000s,d_2010s),
            colors = scales::col_numeric(
               palette = c("#ffffff", "#f2fbd2", "#c9ecb4", "#93d3ab", "#35b0ab"),
               domain = NULL
               ) 
            ) %>%
         tab_header (title =  md("**Banana Yields Across Regions**")) %>%
         tab_source_note ("Table: Joel Soroos @soroosj  | Data: Our World in Data") %>%
         tab_spanner(
           label = "Yields by Decade",
           columns = vars(d_1960s,d_1970s,d_1980s,d_1990s,d_2000s,d_2010s)
            ) %>%
      gtsave("crops.png")
```