---
title: "Cocktails"
author: "Joel Soroos"
date: "June 10, 2020"
output: html_document
---

### 1. Source data
```{r source, warning = TRUE, results = TRUE, message = FALSE}

   library(tidyverse)

   cocktails_raw <- read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-26/boston_cocktails.csv')
   
   #cocktails_raw
```


#### Similar ingredients with different spellings can be consolidated.
```{r}

   cocktails <- cocktails_raw %>%
      mutate (
         ingredient = case_when (
            ingredient == "Fresh lemon juice" ~ "Lemon Juice",
            ingredient == "Juice of a Lemon" ~ "Lemon Juice",
            ingredient == "Fresh Lime Juice" ~ "Lime Juice",
            ingredient == "Juice of a Lime" ~ "Lime Juice",
            ingredient == "Powdered Sugar" ~ "Simple Syrup",
            ingredient == "Egg White" ~ "Egg",
            ingredient == "Whole Egg" ~ "Egg",
            ingredient == "Egg Yolk" ~ "Egg",
            TRUE ~ ingredient)
              )

``` 

```{r}
   ingredients_all <- cocktails %>%
      count (ingredient, sort = T)

   ingredients_top <- ingredients_all %>%
      pull (ingredient) %>%
      head (8)
```


#3a.  upsetR
```{r}

   library(UpSetR)

   #https://timothykylethomas.me/post/r_notebook/tidytuesday22/tidytuesday22/
   #https://www.r-bloggers.com/upset-plots/

   cocktails_matrix <- cocktails %>%
      select (name, ingredient) %>%
      filter (ingredient %in% ingredients_top) %>%
      mutate (ingredient_population = TRUE) %>%
      pivot_wider (
         id_cols = name,
         names_from = ingredient, 
         values_from = ingredient_population, 
         values_fill = FALSE,
         values_fn = length
         ) %>%
      as.data.frame()
   
      upset(
         data = cocktails_matrix, 
         order.by = c("freq"),
         nsets = 8, nintersects = 30
         )
```


#3b.  ggupset
```{r}

   library (ggupset)

   cocktails_list <- cocktails %>%
      group_by (name) %>%
      filter (ingredient %in% ingredients_top) %>%
      summarize(ingredient = list(ingredient))
 
      ggplot(cocktails_list, aes(x=ingredient)) +
      geom_bar() +
      scale_x_upset(n_intersections = 30) +
      theme (
         plot.title = element_text(hjust = 0.5, vjust = 0, size = 14, face = "bold", margin = margin (0,0,15,0)),
         plot.title.position = "plot",
         plot.subtitle = element_text(hjust = 0.5, vjust = 0, size = 6, margin = margin (0,0,2,0)),
         plot.caption = element_text(hjust = 1, size = 8, face = "plain", margin = margin (15,0,0,0)),
         plot.caption.position = "plot",
         axis.title.y = element_text(margin = margin(0,10,0,0)),
         axis.text.x=element_blank(),
         axis.text.y=element_text(size = 7),
         axis.ticks.x=element_blank(),
         legend.position = "none"
         ) +
      labs(
         title = "Most popular alcoholic mixers",
         x = "Ingredient intersection",
         y = "# of drinks",
         caption = "Each column represents unique combinations of ingredients.  Universe is drinks in the Boston Bartender's Guide.\nVisualization: Joel Soroos @soroosj  |  Data: Mr. Boston Bartender's Guide via Kaggle via R4DS Tidy Tuesday"
         ) +
      ggsave("cocktails.png", width = 10, height = 18, units = "cm")
```
