---
title: "Seattle Pets"
output: html_document
---

### 1. Load packages
```{r setup}
knitr::opts_chunk$set(echo = TRUE)

library (tidyverse)
library (ggthemes)
library (ggtextures)
library (magick)

```

### 2. Source data 
```{r import, echo = TRUE} 
pets <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-03-26/seattle_pets.csv")

```

### 3. Identify most popular dog breeds
```{r popular}

pets_summ <- pets %>%
   drop_na () %>%
   filter (species == "Dog") %>%
   group_by (primary_breed) %>%
   summarize (count = n ()) %>%
   arrange (-count) %>%
   head (10)

pets_summ

```

### 4. Load dog images
```{r images}

pets_summ$image <- list (
   image_read ("https://www.petinsurancereview.com/sites/default/files/inline-images/Labrador%20Retriever%202.jpg"),
   image_read ("http://www.allsmalldogbreeds.com/breeds/chihuahua-short-coat.jpg"),
   image_read ("https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/12133017/Golden-Care.jpg"),
   image_read ("https://bowwowinsurance.com.au/wp-content/uploads/2018/10/australian-aussie-terrier-700x700.jpg"),
   image_read ("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRjJqstuFnEQYpXeNbb3Sqv6l5EHxE1TWrEkFwnsW8zMwiIEiwn"),
   image_read ("https://previews.123rf.com/images/fotojagodka/fotojagodka1311/fotojagodka131100256/23734288-miniature-poodle-puppy-sits-on-a-white-background.jpg"),
   image_read ("https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Female_German_Shepherd.jpg/330px-Female_German_Shepherd.jpg"),
   image_read ("https://cf-s3.petcoach.co/uploads/breed/48/1520278916-Aussie2.jpg"),
   image_read ("https://dailystormer.name/wp-content/uploads/2017/12/840dfdd1804b7291c59af3ae134660d8-bully-pitbull-pitbull-terrier.jpg"),
   image_read ("https://s3.amazonaws.com/cdn-origin-etr.akc.org/wp-content/uploads/2017/11/12212849/Australian-Cattle-Dog-History-06.jpg")
      )

``` 

### 5. Create chart 
```{r chart}

pets_bar <- ggplot(pets_summ, aes(x=reorder(primary_breed,count), y=count, image = image)) +
      geom_textured_col (img_height = grid::unit(1,"null"), img_width = grid::unit(0.6,"cm"), ncol = 1, nrow = 1, hjust = 0, vjust = 0.5, fill = "light blue") + 
      theme_economist () +
      theme(
         axis.title.x=element_blank(),
         axis.title.y=element_blank(),
         axis.text.y=element_blank()) +
      labs(
         title = "Most popular dog breeds",
         subtitle = "Seattle: April 2017 - September 2018",
         caption = "Source: City of Seattle") +
      coord_flip ()

ggsave("breeds.png", pets_bar)
pets_bar  

```