----
   title: "Womens World Cup"
   author: "Joel Soroos"
   date: "July 14, 2019"
   output: pdf_document
---

### 1. Source data
```{r source, warning = TRUE, results = FALSE, message = FALSE}

   library (tidyverse)
   library (janitor) 

   outcomes_raw <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-07-09/wwc_outcomes.csv") %>%
      clean_names () 
```
   
   
### 2a. Create list of teams in the 2019 world cup sorted by games played
```{r transform, message = F}

   teams_2019 <- outcomes_raw %>%
     filter (
        year == 2019,
        round != "Third Place Playoff"  
        ) %>%
     mutate (
        win_status_num = 
           case_when (
             win_status == "Won" ~ 3,
             win_status == "Tie" ~ 2,
             win_status == "Lost" ~ 1
         )
      )%>%
     group_by (team) %>%
     tally (win_status_num, sort = T) %>%
     pull (team)
```


### 2b. Transform game outcomes data
```{r transform, message = F}
  outcomes <- outcomes_raw %>%
     filter (
        year > 1990,
        team %in% teams_2019,
        round != "Third Place Playoff" 
         ) %>%
     mutate(
        year = as.factor (year),
        year = fct_relevel(year, "2019", "2015", "2011", "2007", "2003", "1999", "1995", "1991"),   #horizontal facet grid order left to right
        team = fct_relevel(team, teams_2019),   #vertical facet grid chart sort order
        win_status = fct_relevel(win_status, "Lost", "Tie", "Won"),         #bar chart sort order
        final = 1           #consistent bar chart height.  Results signified by color.
         ) %>%
     group_by (year, team) %>%
     mutate (game_team_id = row_number())   #game number for each team within World Cup year.
```


#3.  Visualize
```{r chart, warning = F, message = F}

   library (ggdark)

   ggplot () +
      geom_col (data = outcomes,
             aes(x = game_team_id, y = final, fill = win_status)
         ) +
      facet_grid(team ~ year, switch = "y") +
      scale_fill_brewer(palette = "Set1") +
      #themes
         dark_mode(theme_minimal()) +
         theme (
            plot.title = element_text(hjust = .5, size = 14, face = "bold"), 
            text = element_text(family = "Arial", color = "grey"),
            strip.text.y = element_text(angle=180, size = 8),
            strip.text.x = element_text (size = 10),
            plot.caption = element_text (size = 7),
            axis.text = element_blank(),
            axis.ticks = element_blank(),
            axis.title = element_blank(),
            legend.position = "None"
            )   +
     labs(
        title = "2019 Women's World Cup Teams Historical Results\n",
        caption = "\nEach bar is a game. From left to right: 3 group games, round of 16, quarterfinal, semifinal and final.  Green=win, blue=tie, red=loss. \nSource: data.world via R4DS Tidy Tuesday.   |   Visualization: Joel Soroos @soroosj"
        ) +
      ggsave("world cup.png", width = 15, height = 9.5, units = "cm")
```

