---
   title: "Commute 2"
   author: "Joel Soroos"
   date: "November 30, 2019"
   output: pdf_document
---


### 1. Source data
```{r source, warning = TRUE, results = FALSE, message = FALSE}

   library(tidyverse)

   commute_raw <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-11-05/commute.csv")
```


### 2a.  Transform data
```{r transform, warning = T, message = F, results = F}

   commute <- commute_raw %>%
      drop_na(state_abb) %>%
      group_by (state_abb, city) %>%
      summarize(
         percent = sum(percent)
         )
```



### 3. Visualize data
```{r visualize}

   library (ggdark)
   library (geofacet)

   ggplot(commute) +
      geom_density (
         aes(x=percent),
         fill = "grey") +
      facet_geo(
         ~ state_abb,
         scales = "free"
         ) +
      dark_mode(theme_minimal()) +
      theme(
         plot.title = element_text(hjust = 0.5, vjust = 0, size = 14, face = "bold", margin = margin (0,0,0,0)),
         plot.subtitle = element_text(hjust = 0.5, vjust = 0, size = 8, margin = margin (0,0,5,0)),
         plot.caption = element_text(hjust = 0, size = 8, face = "plain", margin = margin (0,0,0,0)),
         axis.title=element_blank(),
         axis.text=element_blank(),
         axis.ticks=element_blank(),
         legend.title=element_blank(),
         legend.text = element_text(size=8, margin = margin (l=-4, unit = "pt")),
         legend.key.size = unit(0.5, "cm"),
         legend.position = c(0.88,0.25),
         legend.box = "horizontal",
         legend.direction = "vertical",
         legend.spacing = unit(0.05, "cm")
         ) +
      labs(
         title = "Healthiest Commuters in the United States (2008-2012)",
         subtitle = "- Walkers and bikers to work tend to live in small towns in Northeast, Midwest and Pacific Coast.\n- The U.S. city with highest percentage is Ithica, NY (45%), followed by State College, PA (40%).",
         caption = "Each point represents a city's percentage bike or walk commuters. Cities displayed > 10%.\nVisualization: Joel Soroos @soroosj  |  Data: U.S. Census Bureau"
         ) +
      ggsave("commute.png", width = 17, height = 11, units = "cm")
```