---
   title: "Commute"
   author: "Joel Soroos"
   date: "November 10, 2019"
   output: pdf_document
---


### 1. Source data
```{r source, warning = TRUE, results = FALSE, message = FALSE}

   library("tidyverse")
   library("ggmap")

   commute_raw <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-11-05/commute.csv")
   
   map_borders <- map_data("state") 
```


### 2a.  Transform data
```{r transform, warning = T, message = F, results = F}

   library (glue)

   commute <- commute_raw %>%
      mutate (
         city_state = glue ("{city}, {state}"),
         city_size = case_when (
            city_size == "Small" ~ "Small City",
            city_size == "Medium" ~ "Medium City",
            city_size == "Large" ~ "Large City",
            TRUE ~ city_size)
         ) %>%
      group_by (city_state, city_size) %>%
      summarize(
         percent = weighted.mean(percent,n),
         n = sum(n)
         ) %>%
      filter (
         !str_detect(city_state, 'Hawaii|Alaska'),
         percent >= 9
         ) 
```


### 2b.  Obtain geocode for cities
```{r}
    
   register_google(key = Sys.getenv("GOOGLE_MAPS_API"))
   
   commute_coord <- commute %>%
      #head (20) %>%
      mutate_geocode (city_state) %>%
      select (city_state, city_size, lon, lat, percent)
```

### 3. Visualize data
```{r visualize}

   library (ggdark)

   ggplot(commute_coord, aes(x= lon, y = lat)) +
      geom_polygon (
         data = map_borders, 
         aes(x = long, y = lat, group = group),
         color = "black", size = 0.05
         ) +
      geom_point(
         data = commute_coord,
         aes (size = percent, color = city_size),
         shape = 16
         ) +
      scale_size_continuous(
         breaks = c(10,20,30, 40),
         labels = c("10%","20%","30%","40%"),
         range = c(.01,5)) +
      dark_mode(theme_minimal()) +
      theme(
         plot.title = element_text(hjust = 0.5, vjust = 0, size = 14, face = "bold", margin = margin (0,0,0,0)),
         plot.subtitle = element_text(hjust = 0.5, vjust = 0, size = 8, margin = margin (0,0,5,0)),
         plot.caption = element_text(hjust = 0, size = 8, face = "plain", margin = margin (10,0,0,0)),
         axis.title=element_blank(),
         axis.text=element_blank(),
         axis.ticks=element_blank(),
         legend.title=element_blank(),
         legend.text = element_text(size=8, margin = margin (l=-4, unit = "pt")),
         legend.key.size = unit(0.5, "cm")
         legend.position = c(0.88,0.25),
         legend.box = "horizontal",
         legend.direction = "vertical",
         legend.spacing = unit(0.05, "cm")
         ) +
      labs(
         title = "Healthiest Commuters in the United States (2008-2012)",
         subtitle = "- Walkers and bikers to work tend to live in small towns in Northeast, Midwest and Pacific Coast.",
         caption = "Each point represents a city's average % bike or walk commuters.  Average is weighted by relative number of bikers and walkers.\nCities displayed with > 10% weighted average bike/walk commuters.\nVisualization: Joel Soroos @soroosj  |  Data: U.S. Census Bureau"
         ) +
      ggsave("commute.png", width = 17, height = 11, units = "cm")
```