---
title: "Coffee"
author: "Joel Soroos"
date: "7/7/2020"
output: html_document
---

### 1. Source data
```{r source, warning = TRUE, results = TRUE, message = FALSE}

   library(tidyverse)
   library(janitor)
   library(knitr)
   
   opts_chunk$set(warning = FALSE, message = FALSE, results = TRUE)
   
   coffee_all <- tidytuesdayR::tt_load('2020-07-07')

   coffee_raw <- coffee_all$coffee_ratings
   
   #https://github.com/Z3tt/TidyTuesday/blob/master/R/2020_16_BestRapArtists.Rmd
   #https://raw.githubusercontent.com/Z3tt/TidyTuesday/master/plots/2020_16/2020_16_BestRapArtists.png
```


### 2.  Explore  data
```{r explore}

   library(skimr)

   coffee_raw %>%
      tabyl (country_of_origin) %>%
      arrange (-percent) %>%
      head(20)

   skim (coffee_raw)

```

### 3.  Transform stage data
```{r transform, warning = TRUE, results = FALSE, message = FALSE}
   
   country_significant <- coffee_raw %>%
      count (country_of_origin) %>%
      filter (n>7) %>%
      arrange (n) %>%
      pull (country_of_origin)   

   coffee <- coffee_raw %>%
      filter (
         total_cup_points>65,
         country_of_origin %in% country_significant
         ) %>%
      mutate (country_of_origin = recode (country_of_origin,
              "United States (Hawaii)" = "USA",
              "United States (Puerto Rico)" = "USA",
              "United States" = "USA",
              "Tanzania, United Republic Of" = "Tanzania"
              )) 
   
   coffee_summ <- coffee %>%
      group_by (country_of_origin) %>% 
      summarize (
         rating_min = min (total_cup_points),
         rating_med = median (total_cup_points),
         rating_n = n ()
         )
   
   coffee_grades <- coffee %>%
      select (country_of_origin, aroma:cupper_points) %>%
      pivot_longer(aroma:cupper_points, names_to = "grade_type", values_to = "grade_rating") %>%
      group_by(grade_type) %>%
      mutate (grade_rating = scale (grade_rating)) %>%
      group_by(country_of_origin, grade_type) %>%
      summarize (grade_med = median(grade_rating))
   
```


### 4a.  Visualize - median
```{r transform, warning = TRUE, results = FALSE, message = FALSE}

   plot_median <- 
      ggplot (coffee_summ, aes (x = 1, y = reorder(country_of_origin, rating_med))) +
         geom_text(
            aes (label = round(rating_med, 1)),
            color = "white", size = 3, hjust = 0
            ) +
         scale_x_discrete(position = "top") +
         theme (
            plot.background = element_rect(fill= "#6F4E37", color = "#6F4E37"),
            panel.background = element_rect(fill= "#6F4E37"),
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            axis.title = element_blank (),
            axis.text.x = element_text (size = 8, hjust = 0, color = "white", angle = 80),
            axis.text.y = element_text (size = 8, color = "white"),
            axis.ticks = element_blank (),
            legend.position = "none"
            ) +
         labs (
            x = "\nTotal",
            y = ""
            )

``` 


### 4b.  Visualize - grade plot
```{r transform, warning = TRUE, results = FALSE, message = FALSE}

   plot_grade <- 
      ggplot (coffee_grades, aes (x = grade_type, y = reorder(country_of_origin, grade_med))) +
         geom_point(
            aes (color = grade_med)
            ) +
         scale_color_gradient (low = "#6F4E37", high = "white") +
         scale_x_discrete(position = "top") +
         theme (
            plot.background = element_rect(fill= "#6F4E37", color = "#6F4E37"),
            panel.background = element_rect(fill= "#6F4E37"),
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            axis.title = element_blank (),
            axis.text.x = element_text (size = 8, hjust = 0, color = "white", angle = 80),
            axis.text.y = element_blank (),
            axis.ticks = element_blank (),
            legend.position = "none"
            ) +
         labs (
            x = "\nGrade Rating",
            y = ""
            )
``` 


### 4c.  Visualize - count plot
```{r}

   plot_count <- 
      ggplot (coffee_summ, aes (x = reorder(country_of_origin, rating_med), y = rating_n)) +
         geom_col(fill = "white", width = .15) +
         coord_flip () +
         theme (
            plot.background = element_rect(fill= "#6F4E37", color = "#6F4E37"),
            panel.background = element_rect(fill= "#6F4E37"),
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            axis.title = element_text (size = 8, hjust = 0.5, color = "white"),
            axis.text.x = element_text (color = "white"),
            axis.text.y = element_blank (),
            axis.ticks.x = element_line (color = "white"),
            axis.ticks.y = element_blank (),
            legend.position = "none"
            ) +
         labs (
            x = "",
            y = "\n# Entries"
            )	  
```


### 4d.  Visualize - distribution plot
```{r transform, warning = TRUE, results = FALSE, message = FALSE}

   plot_distrib <-
      ggplot (coffee, aes (x = total_cup_points, y = reorder(country_of_origin, total_cup_points))) +
         geom_point(shape = "|", color = "white") +
         theme (
            plot.background = element_rect(fill= "#6F4E37", color = "#6F4E37"),
            panel.background = element_rect(fill= "#6F4E37"),
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            axis.title = element_text (size = 8, hjust = 0.5, color = "white"),
            axis.text.x = element_text (color = "white"),
            axis.text.y = element_blank (),
            axis.ticks.x = element_line (color = "white"),
            axis.ticks.y = element_blank(),
            legend.position = "none"
            ) +
         labs(
            x = "\nOverall Rating Distribution",
            y = ""
            )
```   


### 4d.  Visualize - combine plots
```{r transform, warning = TRUE, results = FALSE, message = FALSE}

   library (patchwork)

   plot_median + plot_grade + plot_count + plot_distrib + plot_layout(widths = c(.13, .44, .4, .65)) +
   plot_annotation (
      caption = "Visualization: Joel Soroos @soroosj  |  Data: Coffee Quality Database via Kaggle via R4DS Tidy Tuesday",
      theme = theme (
         plot.background = element_rect(fill= "#6F4E37", color = "#6F4E37"),
         plot.title = element_blank(),
         #plot.title = element_text(hjust = 0.5, vjust = 0, size = 14, face = "bold", margin = margin (0,0,7,0), color = "white"),
         #plot.subtitle = element_text (hjust = 0.5, vjust = 0, size = 10, margin = margin (0,0,25,0), color = "white"),
         plot.caption = element_text (hjust = 1, size = 7, margin = margin (20,0,0,0), color = "white")
         )
      )
   ggsave("coffee.png")
``` 