---
title: "Plastic Waste"
author: "Joel Soroos"
date: "May 26, 2019"
output:
  pdf_document: default
  html_document: default
---

### 1. Load packages
```{r setup, warning = FALSE, results = FALSE, message = FALSE}

   library (tidyverse)
   library (janitor)
   library (ggrepel)
   library (scales)
   library (kableExtra)
   
```


### 2. Get data
```{r source, warning = TRUE, results = FALSE, message = FALSE}
   
   mismanaged_vs_gdp<- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/per-capita-mismanaged-plastic-waste-vs-gdp-per-capita.csv") %>%
      clean_names()
   
   coast_vs_waste <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/coastal-population-vs-mismanaged-plastic.csv") %>%
      clean_names()

```


### 3. Transform data
```{r transform}

   waste_raw <- left_join (mismanaged_vs_gdp, coast_vs_waste, by = c("code", "year")) %>%
      filter (year == 2010)
   
   waste <- waste_raw %>%
      filter (year == 2010) %>%
      drop_na () %>%
      rename (
         country_name = entity.x,
         waste = mismanaged_plastic_waste_tonnes,
         gdp_per_capita = gdp_per_capita_ppp_constant_2011_international_rate,
         population = total_population_gapminder.x
         )%>%
      mutate (
          waste_per_coastal_capita = waste / coastal_population * 100,
          population = population / 1000000
         ) %>%
      select (country_name, waste, coastal_population, waste_per_coastal_capita,  gdp_per_capita, population) %>%
      arrange (-waste_per_coastal_capita)
   
   kable (head(waste,10))

```

### 4. Visualize
```{r plot}

   ggplot (waste,
      aes(x = gdp_per_capita, y = waste_per_coastal_capita, size = population)) +
      geom_point () +
      geom_smooth () +
      #scales
         scale_x_continuous(
            label = unit_format(prefix = "$", unit = "K", scale = 1e-3, sep = ""),
            trans = log10_trans()
            ) +
         scale_y_continuous(trans = log10_trans()) +
         scale_size_continuous(breaks = c(10, 100, 1000)) +
      theme(
         plot.title = element_text(hjust=0, size = 14),
         plot.caption = element_text(color="black", size=8),
         legend.title = element_text(colour="black", size=9),
         legend.text = element_text(colour="black", size=9),
         legend.position = "top",
         axis.title=element_text(size=9),
         panel.grid.major = element_line(size = 0.05, linetype = 'solid', color = 'grey50'),
         panel.grid.minor = element_blank (),
         panel.background = element_rect(fill = "white")
         ) +
      guides(size = guide_legend(override.aes = list(linetype = 0))) +
      geom_label_repel(
         aes (label = "India's waste lower than predicted \nfor its per capita GDP"),
         data = subset (waste, country_name == "India"),
         box.padding = 0.8, 
         point.padding = 0.7,
         size = 3,
         alpha = .8,
         segment.color = 'grey50'
         ) +
       labs(
         title = "Mismanaged waste decreases as nations reach middle income",
         caption = "\n Sources: National Geographic, Gapminder, R4DS Tidy Tuesday
         Visualization: Joel Soroos (Twitter: @soroosj)",
         x = "GDP per capita",
         y = "Mismanaged waste per coastal capita (100 kg/year)",
         size = "Population (millions): "
         ) +
   ggsave("plot1.png")

```
