---
title: "Big Mac Index"
author: "Joel Soroos"
date: "12/22/2020"
output: html_document
---


##1. Source data
```{r source, warning = FALSE, message = FALSE}

   library(tidytuesdayR)
   library(janitor)

   tuesdata <- tidytuesdayR::tt_load('2020-12-22') 
   
   big_mac_raw <- tuesdata$`big-mac` %>%
      clean_names()
   
   #remove scientific notation
   options(scipen=999)
```


##2. Explore data
```{r skim, warning = F, message =F}

   library(skimr)

   skim (big_mac_raw)
```


##3a. Simplify Big mac file
```{r transform, message = F}

   library(tidyverse)
  
   big_mac <- big_mac_raw %>%
      rename (
         country_code = iso_a3,
         country_name = name,
         currency = currency_code,
         price_loc = local_price,
         price_usd = dollar_price,
         fx_actual = dollar_ex,
         ) %>%
      mutate (
         price_loc = round (price_loc, 2),
         fx_actual = round (fx_actual, 3),
         price_usd = round (price_usd, 2)
      ) %>%
      select (date, country_name, currency, price_loc, price_usd, fx_actual)
```


#3b.  Join non-USD Big Mac prices with USD prices
```{r}

   #source Big Mac prices in USD per each date
   big_mac_usd <- big_mac %>%
      filter (currency == "USD") %>%
      select (date, price_usd) %>%
      rename (price_usd_actual = price_usd)

   #join Big Mac price in USD with GBP for each date
   big_mac_gbp <- big_mac %>%
      filter (currency == "GBP") %>%
      left_join (big_mac_usd, by = "date") %>%
      rename (price_usd_implied = price_usd) %>%
      mutate(
         fx_implied = price_loc / price_usd_actual,
         fx_arbitrage = (fx_implied - fx_actual) / fx_actual
         ) %>%
      select (date, price_loc, price_usd_actual, price_usd_implied, fx_actual, fx_implied, fx_arbitrage) 
```


#4.  Visualize
```{r}

   library (heatwaveR)
   library (here)
   library (ggdark)

   ggplot (big_mac_gbp, aes(x=date)) +
      #periods in which fx_actual > fx_implied
         geom_flame (aes (y = fx_implied, y2 = fx_actual), fill = "red") +
      #periods in which fx_actual < fx_implied
         geom_flame (aes (y2 = fx_implied, y = fx_actual), fill = "green") + 
      geom_line(
          aes (y = fx_implied),
          size = 0.5, linetype = 1, color = "black"
          ) +
      geom_line(
         aes (y = fx_actual),
         size = 0.5, linetype = 1, color = "white"
          ) +
      annotate(
         geom="text", x= as.Date("2018-04-30", "%Y-%m-%d"), y=0.68, 
         label = "GBP undervalued", color="black", size=3, hjust=0.5, vjust=0.5, fontface="bold",
         ) +
      annotate(
         geom="text", x= as.Date("2001-08-30", "%Y-%m-%d"), y=0.72, 
         label = "GBP\novervalued", color="black", size=3, hjust=0.5, vjust=0, fontface="bold"
         ) +
      annotate(
         geom="text", x= as.Date("2003-03-30", "%Y-%m-%d"), y=0.6, 
         label = "Actual FX rate", color="white", size=3, hjust=0.5, vjust=0, fontface="bold", angle = 295
         ) +
      annotate(
         geom="text", x= as.Date("2004-08-30", "%Y-%m-%d"), y=0.66, 
         label = "Implied FX rate", color="white", size=3, hjust=0.5, vjust=0, fontface="bold", angle = 312
         ) +
      dark_theme_classic () +
         theme(
            plot.title = element_text(hjust = 0, vjust = 0, size = 19, face = "bold", margin = margin (0,0,4,0)),
            plot.title.position = "plot",
            plot.subtitle = element_text(hjust = 0, vjust = 0, size = 9, face = "bold", margin = margin (0,0,30,0)),
            plot.caption = element_text (hjust = 0, size = 8, face = "plain", margin = margin (20,0,0,0), color="white"),
            plot.caption.position = "plot",
            panel.grid.major = element_line(colour="white", size=0.03),
            axis.title.y = element_text (size = 9, hjust = 0.5),
            axis.title.x = element_blank(),
            ) +
      labs(
         title = "Forecasting currency movements via the Big Mac Index",
         subtitle = "- Purchasing power parity theorizes the exchange rate between two currencies in long run should match ratio of prices\n  for a comparable good such as a McDonald's Big Mac hamburger.  If relative prices in one country are higher,\n  that country's currency will ultimately appreciate.",
         y = "GBP per USD",
         caption = "Visualization: Joel Soroos @soroosj  |  Data: The Economist via R4DS Tidy Tuesday"
         ) +
      ggsave(
         here("2020-12-22","output","bigmac.png"),
         width = 20, height = 14, units = "cm"
         )
```