---
title: "Big Mac Index"
author: "Joel Soroos"
date: "12/22/2020"
output: html_document
---


##1. Source data
```{r source, warning = FALSE, message = FALSE}

   library(tidytuesdayR)
   library(janitor)

   tuesdata <- tidytuesdayR::tt_load('2020-12-22') 
   
   big_mac_raw <- tuesdata$`big-mac` %>%
      clean_names()
```


##2. Explore data
```{r skim, warning = F, message =F}

   library(skimr)

   skim (big_mac_raw)
```


##3a. Transform data
```{r transform, message = F}

   library(tidyverse)
   library (glue)

   crops <- crops_raw %>%
      pivot_longer (cols = 4:14, names_to = "commodity", values_to = "yield") %>%
      rename (country = entity) %>%
      mutate (
         commodity = if_else (commodity == "cocoa_beans_tonnes_per_hectare", word(commodity, 1, sep = "_"), word (commodity, sep = "_")),
         commodity = str_to_title(commodity),
         decade = glue("d_{floor(year/10)*10}s")
         ) %>%
      drop_na () %>%
      filter (commodity == "Bananas")%>%
      select (country, commodity, decade, year, yield)
```


##3b. Calculate medians by decade
```{r}
   
   crops_mean <- crops %>%
      group_by (country, decade) %>%
      summarize (mean = round(mean (yield),1)) %>%
      pivot_wider (names_from = decade, values_from = mean) %>%
      ungroup() %>%
      rowwise(country) %>%
      mutate (
         mean = mean (c(d_1960s,d_1970s,d_1980s,d_1990s,d_2000s,d_2010s), na.rm = T),
         mean = round (mean, 1),
         plot_image = NA
         ) %>%
      arrange (-mean) %>%
      rowid_to_column("rank") %>%
      head (15) 
```


##4. Visualize
```{r}



```