---
title: "Penguins"
author: "Joel Soroos"
date: "9/30/2020"
output: html_document
---


```{r source, warning = FALSE, message = FALSE}

   library(tidyverse)
   library(janitor)
   library(palmerpenguins)

   penguins_raw <- read_csv(path_to_file("penguins_raw.csv")) %>%
      clean_names()
```


```{r explore}

   library(skimr)

   skim (penguins_raw)
```


```{r transform}

   penguins <- penguins_raw %>%
      rename (
         bill_length = culmen_length_mm,
         bill_depth = culmen_depth_mm,
         flipper_length = flipper_length_mm,
         body_mass = body_mass_g
         ) %>%
      mutate (
         id = row_number(),
         species = word (species, 1),
         bill_length = scale(bill_length),
         bill_depth = scale(bill_depth),
         flipper_length = scale(flipper_length),
         body_mass = scale(body_mass)
         ) %>%
      select (id, species, island, bill_length, bill_depth, flipper_length, body_mass) %>%
      drop_na
```


#Identify optimal number of clusters.
```{r model}

   library(broom)
   library(here)
   
   set.seed(150)
   
   #https://www.tidymodels.org/learn/statistics/k-means/
   #https://www.guru99.com/r-k-means-clustering.html
   
   penguins_clust_all <- 
      tibble (k = 1:10) %>%
      mutate (
         cluster = map(k, ~kmeans(penguins[4:7], .x)),
         tidied = map(cluster, tidy),
         glanced = map(cluster, glance),
         augmented = map(cluster, augment, penguins)
         )
   
   penguins_clusterings <- penguins_clust_all %>%
      unnest (glanced) %>%
      select (-cluster, -tidied, -augmented) %>%
      clean_names %>%
      write_csv (here("2020-07-28","output", "model.csv"))
   
   penguins_clusters <- penguins_clust_all %>%
      unnest (tidied, names_repair = "unique") %>%
      rename (cluster = cluster...9) %>%
      select (-cluster...2, -glanced, -augmented) %>%
      relocate (cluster, .after = k) %>%
      write_csv (here("2020-07-28","output", "clusters.csv"))
   
   # penguins_assignments <- penguins_clust_all %>%
   #    unnest (augmented) %>%
   #    select (-cluster, -glanced, -tidied) %>%
   #    rename (cluster = .cluster) %>%
   #    relocate (cluster, .after = k)  %>%
   #    write_csv (here("2020-07-28","output", "assignments.csv"))
```

#Calculate k-means for optimized 3 clusters
```{r}
   penguins_kmeans <- kmeans(penguins[4:7], 3)

   penguins_kmeans_extended <- penguins_kmeans %>%
      augment (penguins) %>%
      rename (cluster = .cluster) %>%
      select (cluster, species, island, id) %>%
      write_csv (here("2020-07-28","output", "assignments.csv"))
```


#Visualize cluster points
```{r}

   library (factoextra)
      
   fviz_cluster(
      penguins_kmeans, geom = "point", data = penguins[4:7]) +
      labs(
         title = "Penguin Clustering",
         caption = "Visualization: Joel Soroos @soroosj  |  Data: palmerpenguins R package"
         ) +
      theme (
         plot.title = element_text (margin = margin(0,0,5,0), hjust = 0.5, size = 15, family = "Lato"),
         plot.subtitle = element_text (margin = margin(0,0,37,0), hjust = 0.5, size = 14, family = "Lato"),
         plot.caption = element_text (margin = margin(36,0,3,0), hjust = 1, size = 8, family = "Lato"),
         plot.background = element_blank(),
         legend.text = element_text(hjust = 0, size = 13, family = "Lato")
         ) +
      ggsave (here("2020-07-28","output", "cluster.png"))
```


```{r}

   penguins_kmeans_extended %>%
      count(species,cluster) %>%
      ggplot(aes(x=species, y=cluster, fill = n)) + 
         geom_tile() +
      ggsave (here("2020-07-28","output", "species_heatmap.png"))

   penguins_kmeans_extended %>%
      count(island,cluster) %>%
      ggplot(aes(x=island, y=cluster, fill = n)) + 
         geom_tile() +
      ggsave (here("2020-07-28","output", "island_heatmap.png"))
```





