---
title: "Grand Slam"
output: html_document
---

### 1. Load packages
```{r setup}
knitr::opts_chunk$set(echo = TRUE)

library (tidyverse)
library (janitor)
library (ggthemes)
library (ggrepel)
library (stringr)

```

### 2. Source data 
```{r source, warning=TRUE}
tennis_raw <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-04-09/grand_slam_timeline.csv")

tennis <- tennis_raw %>%
   clean_names() %>%
   mutate(
     outcome_num = case_when(
        outcome == "Won" ~ 8,
        outcome == "Finalist" ~ 7,
        outcome == "Semi-finalist" ~ 6,
        outcome == "Quarterfinalist" ~ 5,
        outcome == "4th Round" ~ 4,
        outcome == "3rd Round" ~ 3,
        outcome == "2nd Round" ~ 2,
        outcome == "1st Round" ~ 1
         )
     )  %>%
   #str_remove (player, "// ") %>%
   drop_na ()



tennis %>%
   head (10)
   
```


```{r aggregate}
  
tennis_avg <- tennis %>%
   group_by (player) %>%
   summarize (
      avg = round(mean (outcome_num),2),
      st_dev = round(sd (outcome_num),2),
      n = n ()
      ) %>%
   arrange (avg) %>%
   drop_na ()

tennis_avg %>%
   arrange (-avg) %>%
   head (10)

tennis_avg %>%
   arrange (-st_dev) %>%
   head (10)
```


```{r chart}

ggplot (tennis_avg, aes (avg, st_dev, label = player)) +
   geom_point () +
   theme_tufte () +
   scale_y_continuous(trans = "reverse") +
   geom_label_repel(
      aes(label=ifelse(avg>6,as.character(player),'')),
      box.padding   = 0.35, 
      point.padding = 0.5,
      size = 3,
      segment.color = 'grey50') +
   labs(
      title = "Average and Dispersion of Grand Slam Outcomes (1968-2018)",
      subtitle = "Win = 8, 1st Round = 1",
      caption = "Source:Wikipedia",
      x = "Average",
      y = "Standard Deviation"
      ) +
   theme(
      axis.title.x=element_text(size=9),
      axis.title.y=element_text(size=9)
   )
      

```
