---
   title: "Dogs"
   author: "Joel Soroos"
   date: "December 29, 2019"
   output: pdf_document
---


### 1a. Source data
```{r source, warning = TRUE, results = FALSE, message = FALSE}

   library(tidyverse)
   library(tidytuesdayR)

   tuesdata <- tidytuesdayR::tt_load('2019-12-17')
   dog_travel_raw <- tuesdata$dog_travel
```


#1b.  Source state information
```{r}

  states <- tibble (
      state_region = state.region,
      state_division = state.division, 
      state_abb = state.abb,
      state_name = state.name
      ) %>%
      arrange (state_region, state_division)
```


#1c.  Source fonts
```{r}

   library (showtext)
   
   font_add_google("Gaegu")
   showtext_auto() 
```


### 2a.  Transform at dog level
```{r transform, warning = T, results = F, message = F}

   dog_travel <- dog_travel_raw %>%
      rename (
         current_state = contact_state,
         prior_state = found
         ) %>%
      mutate (
         prior_state = ifelse (is.na (manual), prior_state, manual),
         prior_state = case_when (
            prior_state == "VA" ~ "Virginia",
            prior_state == "MD" ~ "Maryland",
            prior_state == "NC" ~ "North Carolina",
            prior_state == "LA" ~ "Louisiana",
            prior_state == "Charlotte" ~ "North Carolina",
            prior_state == "NM" ~ "New Mexico",
            prior_state == "NJ" ~ "New Jersey",
            TRUE ~ prior_state)
         ) %>%
      inner_join (states, by = c("prior_state" = "state_name")) %>%
      inner_join (states, by = c("current_state" = "state_abb")) %>%
      filter (current_state %in% state_abb) %>%
      select (state_abb, state_region.x, current_state, state_region.y, id) %>%
      rename (
         prior_state = state_abb,
         prior_region = state_region.x,
         current_region = state_region.y
         )
```


### 2b.  Transform at region level
```{r}

   dog_travel_prior <- dog_travel %>%
      group_by (prior_region) %>%
      tally(sort = T) %>%
      mutate(freq = round(n / sum(n) * 100,1))

   dog_travel_current <- dog_travel %>%
      group_by (current_region) %>%
      filter (prior_region == "South") %>%
      tally(sort = T) %>%
      mutate(freq = round(n / sum(n) * 100,1))

   dog_travel_flow <- dog_travel %>%
      group_by(prior_region, current_region) %>%
      tally (sort = T)
```


### 3. Visualize
```{r visualize, message = F, warning = T}

   library(ggalluvial)
   library(viridis)
   library(glue)

   ggplot(data = dog_travel_flow, aes(axis1 = prior_region, axis2 = current_region, y = n)) +
      geom_alluvium(
         aes (fill = prior_region),
         alpha = 0.8, decreasing = F
         ) +
      geom_stratum(decreasing = F) +
      geom_text(stat = "stratum", infer.label = TRUE, size = 2.5, decreasing = F, family = "Gaegu") +
      scale_fill_viridis(discrete = T) +
      theme (
         panel.background = element_rect(fill= "white"),
         plot.title = element_text(hjust = 0.5, vjust = 0, size = 11, face = "bold", margin = margin (0,0,5,0)),
         plot.title.position = "plot",
         plot.subtitle = element_text(hjust = 0.5, vjust = 0, size = 6, margin = margin (0,0,2,0)),
         plot.caption = element_text(hjust = 0, size = 6, face = "plain", margin = margin (5,0,0,0)),
         plot.caption.position = "plot",
         axis.title.y = element_text(margin = margin(0,10,0,0)),
         axis.text.x=element_blank(),
         axis.text.y=element_text(size = 7),
         axis.ticks.x=element_blank(),
         legend.position = "none",
         text = element_text(family = "Gaegu")
         ) +
      labs(
         title = "Your dog's bark likely has a Southern accent",
         subtitle = glue ("{dog_travel_prior [1,3]}% of all U.S. adoptable dogs were born in the South.\nOf the Southern dogs,{dog_travel_current[1,3]}% stayed in the South, while {dog_travel_current[2,3]}%, {dog_travel_current[3,3]}%, {dog_travel_current[4,3]}% migrated to Northeast, North Central and West respectively."),
         y = "# of Adoptable Dogs",
         caption = "Left column is birth region of the dog.  Right column is the region dog is available for adoption.\nUniverse is adoptable dogs in U.S. on Petfinder.com as of September 9, 2019.\nVisualization: Joel Soroos @soroosj  |  Data: The Pudding via R4DS Tidy Tuesday"
         ) +
      ggsave("dogs.png", width = 12.5, height = 8, units = "cm")
```