---
title: "Spotify"
author: "Joel Soroos"
date: "January 28, 2020"
output: html_document
---

#Idea from Cal Webb: http://calumwebb.uk/posts/spotifyr/

#1.  Source data
```{r source, include=FALSE}
   knitr::opts_chunk$set(echo = TRUE)

   library(tidytuesdayR)
   library(janitor)

   tuesdata <- tidytuesdayR::tt_load('2020-01-21')
   songs_raw <- tuesdata$spotify_songs %>%
      clean_names() 
```


#2a.  Isolate required fields, observations
```{r core data, warning = F, results = F, message = F, echo = T}

   library(tidyverse)  
   library(glue)
 
   songs_unique <- songs_raw %>% 
      mutate(
         track_name_artist = glue ('{track_name} - {track_artist}')
         ) %>% 
      filter(
         !duplicated(track_name_artist),
         playlist_genre == "rock",
         track_popularity > 0
         )
      
   songs <- songs_unique %>%
      mutate (track_rank = rank(-track_popularity)) %>%
      filter  (
         track_rank < 25
         ) %>%
      column_to_rownames("track_name_artist") %>%
      select(danceability, energy, loudness, mode, speechiness, acousticness, instrumentalness, liveness, valence, tempo)
```


#2b.  Create distance matrix and clusters
```{r cluster, warning = F, results = F, message = F, echo = T}

   library (broom)

   songs_distance <- dist(songs)
   songs_distance_tidy <- tidy (songs_distance)
   
   songs_cluster <- hclust(songs_distance)
```


#2c.  Create dendogram components
```{r cluster, warning = F, results = F, message = F, echo = T}

   library(ggdendro)

   songs_dendro <- songs_cluster %>%
      as.dendrogram() %>%
      dendro_data(type = "rectangle")
   
   songs_dendro_segment <- segment(songs_dendro)
   songs_dendro_label <- 
      label(songs_dendro) %>%
      left_join (songs_unique, by = c("label" = "track_name_artist")) %>%
      select (x,y, label, playlist_subgenre)
      
```


#3.  Visualize
```{r visualize, warning = F, results = F, message = F, echo = T}
   
   ggplot() + 
      geom_segment(
         data = songs_dendro_segment,
         aes(x = x, y = y, xend = xend, yend = yend)
         ) + 
      geom_text(
         data = songs_dendro_label,
         aes(x = x, y = y, label = label, color = playlist_subgenre, hjust = 0),
         size = 2
         ) +
      coord_flip() + 
      scale_y_reverse(expand = c(0.2, 0)) +
      theme_dendro() +
      ggsave('songs.png')

```   